<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class WorkTeamClassificationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('work_team_classifications')->insert([
            [
                'id' => 1,
                'work_team_id' => 6,
                'name' => 'Penyusunan Kebijakan, Program dan Wilayah',
                'code' => 'RC.000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'work_team_id' => 6,
                'name' => 'Kebijakan Pembangunan Pertanian',
                'code' => 'RC.010',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'work_team_id' => 6,
                'name' => 'Rencana dan Program Pembangunan Pertanian',
                'code' => 'RC.020',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'work_team_id' => 6,
                'name' => ' Penetapan Kinerja Tahunan',
                'code' => 'RC.030',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'work_team_id' => 6,
                'name' => ' Pengembangan Wilayah',
                'code' => 'RC.040',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'work_team_id' => 6,
                'name' => '  Penyusunan Anggaran',
                'code' => 'RC.100',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'work_team_id' => 6,
                'name' => 'Penyusunan Anggaran Kantor Pusat',
                'code' => 'RC.110',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'work_team_id' => 6,
                'name' => 'Penyusunan Anggaran Dana Dekonsentrasi',
                'code' => 'RC.120',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'work_team_id' => 6,
                'name' => 'Penyusunan Anggaran Dana Tugas Pembantuan',
                'code' => 'RC.130',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'work_team_id' => 6,
                'name' => 'Penyusunan Anggaran Unit Pelaksana Teknis (UPT)',
                'code' => 'RC.140',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'work_team_id' => 6,
                'name' => 'Pemantauan dan Evaluasi Program',
                'code' => 'RC.200',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'work_team_id' => 6,
                'name' => 'Program Bersumber dari APBN',
                'code' => 'RC.210',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'work_team_id' => 6,
                'name' => 'Program Bersumber Dari Dana Dekonsentrasi',
                'code' => 'RC.220',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'work_team_id' => 6,
                'name' => 'Program Bersumber Dari Dana Tugas Pembantuan',
                'code' => 'RC.230',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'work_team_id' => 6,
                'name' => 'Program Bersumber Dari Dana Alokasi Khusus (DAK)',
                'code' => 'RC.240',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 16,
                'work_team_id' => 6,
                'name' => 'Program Bersumber Dari Dana Public Service Obligation (PSO)',
                'code' => 'RC.250',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 17,
                'work_team_id' => 6,
                'name' => 'Program Bersumber Dari Dana Kredit Program',
                'code' => 'RC.260',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 18,
                'work_team_id' => 6,
                'name' => 'Program Bersumber Dari Dana Subsidi',
                'code' => 'RC.270',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 19,
                'work_team_id' => 6,
                'name' => 'Program Bersumber Dari Anggaran Lainnya',
                'code' => 'RC.280',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 20,
                'work_team_id' => 6,
                'name' => 'Pelaporan',
                'code' => 'RC.300',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 21,
                'work_team_id' => 6,
                'name' => 'Laporan Khusus',
                'code' => 'RC.310',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 22,
                'work_team_id' => 6,
                'name' => 'Laporan Berkala',
                'code' => 'RC.320',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 23,
                'work_team_id' => 6,
                'name' => 'Laporan Kinerja',
                'code' => 'RC.330',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 24,
                'work_team_id' => 3,
                'name' => 'Organisasi',
                'code' => 'OT.000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 25,
                'work_team_id' => 3,
                'name' => 'Organisasi Kementerian Pertanian',
                'code' => 'OT.010',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 26,
                'work_team_id' => 3,
                'name' => 'Organisasi Unit Pelaksana Teknis (UPT)',
                'code' => 'OT.020',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 27,
                'work_team_id' => 3,
                'name' => 'Organisasi Satuan Kerja Perangkat Daerah (SKPD)',
                'code' => 'OT.030',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 28,
                'work_team_id' => 3,
                'name' => 'Rincian Tugas Pekerjaan',
                'code' => 'OT.040',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 29,
                'work_team_id' => 3,
                'name' => 'Organisasi Non Struktural',
                'code' => 'OT.050',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 30,
                'work_team_id' => 3,
                'name' => 'Organisasi Non Kedinasan',
                'code' => 'OT.060',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 31,
                'work_team_id' => 3,
                'name' => 'Budaya Kerja',
                'code' => 'OT.070',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 32,
                'work_team_id' => 3,
                'name' => 'Pelayanan Publik',
                'code' => 'OT.080',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 33,
                'work_team_id' => 3,
                'name' => 'Jabatan Fungsional',
                'code' => 'OT.100',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 34,
                'work_team_id' => 3,
                'name' => 'Jabatan Fungsional Rumpun Ilmu Hayat Pertanian (RIHP)',
                'code' => 'OT.110',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 35,
                'work_team_id' => 3,
                'name' => 'Jabatan Fungsional Non Rumpun Ilmu Hayat Pertanian (Non- RIHP)',
                'code' => 'OT.120',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 36,
                'work_team_id' => 3,
                'name' => 'Tata Laksana',
                'code' => 'OT.200',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 37,
                'work_team_id' => 3,
                'name' => 'Prosedur Kerja',
                'code' => 'OT.210',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 38,
                'work_team_id' => 3,
                'name' => 'Tata Hubungan Kerja',
                'code' => 'OT.220',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 39,
                'work_team_id' => 3,
                'name' => 'Pembakuan Sarana Kerja',
                'code' => 'OT.230',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 40,
                'work_team_id' => 3,
                'name' => 'Reformasi Birokrasi',
                'code' => 'OT.240',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 41,
                'work_team_id' => 1,
                'name' => 'Pengadaan Barang',
                'code' => 'PL.000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 42,
                'work_team_id' => 1,
                'name' => 'Pengadaan Barang Bergerak',
                'code' => 'PL.010',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 43,
                'work_team_id' => 1,
                'name' => 'Pengadaan Barang Tidak Bergerak',
                'code' => 'PL.020',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 44,
                'work_team_id' => 1,
                'name' => 'Pengadaan Barang Habis Pakai',
                'code' => 'PL.030',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 45,
                'work_team_id' => 1,
                'name' => 'Pengadaan Barang Tak Berwujud',
                'code' => 'PL.040',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 46,
                'work_team_id' => 1,
                'name' => 'Pemindahtanganan',
                'code' => 'PL.100',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 47,
                'work_team_id' => 1,
                'name' => 'Penjualan ',
                'code' => 'PL.110',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 48,
                'work_team_id' => 1,
                'name' => 'Tukar Menukar',
                'code' => 'PL.120',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 49,
                'work_team_id' => 1,
                'name' => 'Hibah',
                'code' => 'PL.130',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 50,
                'work_team_id' => 1,
                'name' => 'Penyertaan Modal Pemerintah',
                'code' => 'PL.140',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 51,
                'work_team_id' => 1,
                'name' => 'Penatausahaan',
                'code' => 'PL.200',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 52,
                'work_team_id' => 1,
                'name' => 'Pembukuan',
                'code' => 'PL.210',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 53,
                'work_team_id' => 1,
                'name' => 'Inventarisasi Penilaian',
                'code' => 'PL.220',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 54,
                'work_team_id' => 1,
                'name' => 'Laporan BMN',
                'code' => 'PL.230',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 55,
                'work_team_id' => 1,
                'name' => 'Pemanfaatan, Penghapusan, Pengawasan, Pengendalian BMN',
                'code' => 'PL.300',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 56,
                'work_team_id' => 1,
                'name' => 'Pemanfaatan',
                'code' => 'PL.310',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 57,
                'work_team_id' => 1,
                'name' => 'Penghapusan',
                'code' => 'PL.320',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 58,
                'work_team_id' => 1,
                'name' => 'Pengawasan dan Pengendalian',
                'code' => 'PL.330',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 59,
                'work_team_id' => 8,
                'name' => 'Program Legislasi Pertanian',
                'code' => 'HK.000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 60,
                'work_team_id' => 8,
                'name' => 'Peraturan Perundang-undangan',
                'code' => 'HK.100',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 61,
                'work_team_id' => 8,
                'name' => 'Undang-Undang atau Peraturan Pemerintah Pengganti Undang-undang dalam Bidang Pertanian',
                'code' => 'HK.110',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 62,
                'work_team_id' => 8,
                'name' => 'Peraturan Pemerintah dalam Bidang Pertanian',
                'code' => 'HK.120',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 63,
                'work_team_id' => 8,
                'name' => 'Peraturan/Keputusan/Instruksi Presiden dalam Bidang Pertanian',
                'code' => 'HK.130',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 64,
                'work_team_id' => 8,
                'name' => 'Peraturan Menteri Pertanian',
                'code' => 'HK.140',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 65,
                'work_team_id' => 8,
                'name' => 'Keputusan/ Instruksi Menteri Pertanian',
                'code' => 'HK.150',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 66,
                'work_team_id' => 8,
                'name' => 'Keputusan/ Instruksi Pimpinan Unit Keria',
                'code' => 'HK.160',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 67,
                'work_team_id' => 8,
                'name' => 'Perjanjian',
                'code' => 'HK.200',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 68,
                'work_team_id' => 8,
                'name' => 'Kesepakatan Bersama',
                'code' => 'HK.210',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 69,
                'work_team_id' => 8,
                'name' => 'Nota kesepahaman/Memorandum of Understanding (MoU)',
                'code' => 'HK.220',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 70,
                'work_team_id' => 8,
                'name' => 'Perjanjian Kerjasama',
                'code' => 'HK.230',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 71,
                'work_team_id' => 8,
                'name' => 'Pembinaan dan Dokumentasi Hukum',
                'code' => 'HK.300',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 72,
                'work_team_id' => 8,
                'name' => 'Pembinaan Hukum',
                'code' => 'HK.310',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 73,
                'work_team_id' => 8,
                'name' => 'Dokumentasi Hukum',
                'code' => 'HK.320',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 74,
                'work_team_id' => 8,
                'name' => 'Bantuan/Konsultasi/Advokasi Hukum',
                'code' => 'HK.400',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 75,
                'work_team_id' => 8,
                'name' => 'Perdata',
                'code' => 'HK.410',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 76,
                'work_team_id' => 8,
                'name' => 'Tata Usaha Negara',
                'code' => 'HK.420',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 77,
                'work_team_id' => 8,
                'name' => 'Pengujian Materiil (Judicial Review)',
                'code' => 'HK.430',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 78,
                'work_team_id' => 8,
                'name' => 'Hak Atas Kekayaan Intelektual (HaKI)',
                'code' => 'HK.500',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 79,
                'work_team_id' => 8,
                'name' => 'Hak Cipta',
                'code' => 'HK.510',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 80,
                'work_team_id' => 8,
                'name' => 'Hak Paten',
                'code' => 'HK.520',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 81,
                'work_team_id' => 8,
                'name' => 'Hak Merk',
                'code' => 'HK.530',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 82,
                'work_team_id' => 8,
                'name' => 'Varietas Tanaman',
                'code' => 'HK.540',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 83,
                'work_team_id' => 8,
                'name' => 'Hak Desain Industri',
                'code' => 'HK.550',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 84,
                'work_team_id' => 8,
                'name' => 'Rahasia Dagang',
                'code' => 'HK.560',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 85,
                'work_team_id' => 8,
                'name' => 'Desain Tata Letak Sirkuit Terpadu',
                'code' => 'HK.570',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 86,
                'work_team_id' => 8,
                'name' => 'Kerjasama Bilateral',
                'code' => 'KL.000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 87,
                'work_team_id' => 8,
                'name' => 'Asia Pasifik',
                'code' => 'KL.010',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 88,
                'work_team_id' => 8,
                'name' => 'Amerika',
                'code' => 'KL.020',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 89,
                'work_team_id' => 8,
                'name' => 'Eropa',
                'code' => 'KL.030',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 90,
                'work_team_id' => 8,
                'name' => 'Afrika',
                'code' => 'KL.040',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 91,
                'work_team_id' => 8,
                'name' => 'Timur Tengah',
                'code' => 'KL.050',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 92,
                'work_team_id' => 8,
                'name' => 'Kerjasama Regional',
                'code' => 'KL.100',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 93,
                'work_team_id' => 8,
                'name' => 'ASEAN',
                'code' => 'KL.110',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 94,
                'work_team_id' => 8,
                'name' => 'NON-ASEAN',
                'code' => 'KL.120',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 95,
                'work_team_id' => 8,
                'name' => 'Intra Kawasan',
                'code' => 'KL.130',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 96,
                'work_team_id' => 8,
                'name' => 'Kerjasama Multilateral',
                'code' => 'KL.200',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 97,
                'work_team_id' => 8,
                'name' => 'PBB',
                'code' => 'KL.210',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 98,
                'work_team_id' => 8,
                'name' => 'Organisasi Internasional Pemerintah dan Non Pemerintah',
                'code' => 'KL.220',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 99,
                'work_team_id' => 8,
                'name' => 'Administrasi Perencanaan',
                'code' => 'KL.230',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 100,
                'work_team_id' => 8,
                'name' => 'Administrasi Perencanaan',
                'code' => 'KL.230',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 101,
                'work_team_id' => 9,
                'name' => 'Keprotokolan',
                'code' => 'HM.000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 102,
                'work_team_id' => 9,
                'name' => 'Kunjungan',
                'code' => 'HM.020',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 103,
                'work_team_id' => 9,
                'name' => 'Dokumentasi dan Penyajian Informasi Kelembagaan',
                'code' => 'HM.100',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 104,
                'work_team_id' => 9,
                'name' => 'Dokumentasi',
                'code' => 'HM.110',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 105,
                'work_team_id' => 9,
                'name' => 'Publikasi',
                'code' => 'HM.120',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 106,
                'work_team_id' => 9,
                'name' => 'Informasi Publik',
                'code' => 'HM.130',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 107,
                'work_team_id' => 9,
                'name' => 'Penerbitan',
                'code' => 'HM.140',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 108,
                'work_team_id' => 9,
                'name' => 'Pameran',
                'code' => 'HM.150',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 109,
                'work_team_id' => 9,
                'name' => 'Pers/ Media Massa',
                'code' => 'HM.160',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 110,
                'work_team_id' => 9,
                'name' => 'Pers/ Media Massa',
                'code' => 'HM.160',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 111,
                'work_team_id' => 9,
                'name' => 'Pendapat umum',
                'code' => 'HM.170',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 112,
                'work_team_id' => 9,
                'name' => 'Bahan/Materi Pidato Pimpinan',
                'code' => 'HM.180',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 113,
                'work_team_id' => 9,
                'name' => 'Perpustakaan',
                'code' => 'HM.190',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 114,
                'work_team_id' => 9,
                'name' => 'Hubungan Antar Lembaga',
                'code' => 'HM.200',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 115,
                'work_team_id' => 9,
                'name' => 'Lembaga Tertinggi Dan Tinggi Negara',
                'code' => 'HM.210',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 116,
                'work_team_id' => 9,
                'name' => 'Lémbaga Pemerintah',
                'code' => 'HM.210',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 117,
                'work_team_id' => 9,
                'name' => 'Organisasi Sosial/ LSM',
                'code' => 'HM.220',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 118,
                'work_team_id' => 9,
                'name' => 'Perusahaan',
                'code' => 'HM.230',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 119,
                'work_team_id' => 9,
                'name' => 'Perguruan Tinggi/ Sekolah',
                'code' => 'HM.240',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 120,
                'work_team_id' => 9,
                'name' => 'Asosiasi/ Organisasi Profesi',
                'code' => 'HM.250',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 121,
                'work_team_id' => 9,
                'name' => 'Badan Koordinasi Kehumasan (Bakohumas)',
                'code' => 'HM.260',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 122,
                'work_team_id' => 2,
                'name' => 'Pelaksanaan Anggaran',
                'code' => 'KU.000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 123,
                'work_team_id' => 2,
                'name' => 'Pejabat Pengelola Keuangan',
                'code' => 'KU.010',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 124,
                'work_team_id' => 2,
                'name' => 'Pendapatan',
                'code' => 'KU.020',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 125,
                'work_team_id' => 2,
                'name' => 'Penerimaan Negara Bukan Pajak (PNBP)',
                'code' => 'KU.030',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 126,
                'work_team_id' => 2,
                'name' => 'Belanja',
                'code' => 'KU.040',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 127,
                'work_team_id' => 2,
                'name' => 'Pembukuan Keuangan',
                'code' => 'KU.050',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 128,
                'work_team_id' => 2,
                'name' => 'Penggajian dan Tunjangan',
                'code' => 'KU.060',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 129,
                'work_team_id' => 2,
                'name' => 'Rekening Pemerintah',
                'code' => 'KU.070',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 130,
                'work_team_id' => 2,
                'name' => 'Laporan Keuangan',
                'code' => 'KU.100',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 131,
                'work_team_id' => 2,
                'name' => 'Laporan Keuangan Bulanan',
                'code' => 'KU.110',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 132,
                'work_team_id' => 2,
                'name' => 'Laporan Keuangan Triwulanan',
                'code' => 'KU.120',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 133,
                'work_team_id' => 2,
                'name' => 'Laporan Keuangan Semesteran',
                'code' => 'KU.130',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 134,
                'work_team_id' => 2,
                'name' => 'Laporan Keuangan Tahunan',
                'code' => 'KU.140',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 135,
                'work_team_id' => 2,
                'name' => 'Bantuan/ Pinjaman Luar Negeri',
                'code' => 'KU.200',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 136,
                'work_team_id' => 2,
                'name' => 'Pertanggungjawaban Keuangan Negara',
                'code' => 'KU.300',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 137,
                'work_team_id' => 2,
                'name' => 'Laporan Hasil Pemeriksaan',
                'code' => 'KU.310',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 138,
                'work_team_id' => 2,
                'name' => 'Dokumen Penyelesaian Keuangan Negara',
                'code' => 'KU.320',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 139,
                'work_team_id' => 3,
                'name' => 'Perencanaan Kebutuhan Pegawai',
                'code' => 'KP.000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 140,
                'work_team_id' => 3,
                'name' => 'Analisis Jabatan/ Beban Kerja',
                'code' => 'KP.010',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 141,
                'work_team_id' => 3,
                'name' => 'Formasi',
                'code' => 'KP.020',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 142,
                'work_team_id' => 3,
                'name' => 'Data Pegawai',
                'code' => 'KP.030',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 143,
                'work_team_id' => 3,
                'name' => 'Pengadaan Pegawai',
                'code' => 'KP.100',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 144,
                'work_team_id' => 3,
                'name' => 'Penerimaan Pegawai',
                'code' => 'KP.110',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 145,
                'work_team_id' => 3,
                'name' => 'Pengangkatan CPNS',
                'code' => 'KP.120',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 146,
                'work_team_id' => 3,
                'name' => 'Pengangkatan PNS',
                'code' => 'KP.130',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 147,
                'work_team_id' => 3,
                'name' => 'Pengangkatan dan Kepangkatan',
                'code' => 'KP.200',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 148,
                'work_team_id' => 3,
                'name' => 'Kenaikan Pangkat Jabatan Struktural',
                'code' => 'KP.210',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 149,
                'work_team_id' => 3,
                'name' => 'Kenaikan Pangkat Jabatan Fungsional',
                'code' => 'KP.220',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 150,
                'work_team_id' => 3,
                'name' => 'Pengangkatan dan Pemberhentian dalam Jabatan Struktural',
                'code' => 'KP.230',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 151,
                'work_team_id' => 3,
                'name' => 'Pengangkatan dan Pemberhentian dalam Jabatan Fungsional',
                'code' => 'KP.240',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 152,
                'work_team_id' => 3,
                'name' => 'Alih Tugas',
                'code' => 'KP.250',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 153,
                'work_team_id' => 3,
                'name' => 'Mutasi Keluarga',
                'code' => 'KP.260',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 154,
                'work_team_id' => 3,
                'name' => 'Peninjauan Masa Kerja',
                'code' => 'KP.270',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 155,
                'work_team_id' => 3,
                'name' => 'Penetapan Perubahan Data Dasar/ Status/ Kedudukan Hukum Pegawai',
                'code' => 'KP.280',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 156,
                'work_team_id' => 3,
                'name' => 'Baperjakat',
                'code' => 'KP.290',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 157,
                'work_team_id' => 3,
                'name' => 'Pembinaan Karier Pegawai',
                'code' => 'KP.300',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 158,
                'work_team_id' => 3,
                'name' => 'Diklat/Kursus/Ujian Dinas/Ujian Kenaikan Pangkat Penyesuaian Ijazah Pegawai',
                'code' => 'KP.310',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 159,
                'work_team_id' => 3,
                'name' => 'Tugas Belajar',
                'code' => 'KP.320',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 160,
                'work_team_id' => 3,
                'name' => 'Izin Belajar Pegawai',
                'code' => 'KP.330',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 161,
                'work_team_id' => 3,
                'name' => 'Penilaian Kinerja Pegawai',
                'code' => 'KP.340',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 162,
                'work_team_id' => 3,
                'name' => 'Kompetensi Pegawai',
                'code' => 'KP.350',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 163,
                'work_team_id' => 3,
                'name' => 'Perselisihan/ Sengketa Kepegawaian',
                'code' => 'KP.360',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 164,
                'work_team_id' => 3,
                'name' => 'Disiplin Pegawai',
                'code' => 'KP.370',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 165,
                'work_team_id' => 3,
                'name' => 'Administrasi Pegawai',
                'code' => 'KP.400',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 166,
                'work_team_id' => 3,
                'name' => 'Pelaksana Tugas/Harian',
                'code' => 'KP.410',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 167,
                'work_team_id' => 3,
                'name' => 'Kartu Identitas Pegawai',
                'code' => 'KP.420',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 168,
                'work_team_id' => 3,
                'name' => 'Keterangan Pegawai',
                'code' => 'KP.430',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 169,
                'work_team_id' => 3,
                'name' => 'Kesejahteraan Pegawai',
                'code' => 'KP.500',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 170,
                'work_team_id' => 3,
                'name' => 'Pemeliharaan Kesehatan Pegawai',
                'code' => 'KP.510',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 171,
                'work_team_id' => 3,
                'name' => 'Tabungan Pensiun (Taspen)',
                'code' => 'KP.520',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 172,
                'work_team_id' => 3,
                'name' => 'Tabungan Perumahan (Bapetarum)',
                'code' => 'KP.530',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 173,
                'work_team_id' => 3,
                'name' => 'Dana Sosial',
                'code' => 'KP.540',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 174,
                'work_team_id' => 3,
                'name' => 'Pakaian Dinas',
                'code' => 'KP.550',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 175,
                'work_team_id' => 3,
                'name' => 'Pengurusan Jenazah',
                'code' => 'KP.560',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 176,
                'work_team_id' => 3,
                'name' => 'Olahraga dan Rekreasi',
                'code' => 'KP.570',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 177,
                'work_team_id' => 3,
                'name' => 'Cuti',
                'code' => 'KP.580',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 178,
                'work_team_id' => 3,
                'name' => 'Penghargaan dan Tanda Jasa',
                'code' => 'KP.590',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 179,
                'work_team_id' => 3,
                'name' => 'Pemberhentian Pegawai',
                'code' => 'KP.600',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 180,
                'work_team_id' => 3,
                'name' => 'Dengan Hormat',
                'code' => 'KP.610',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 181,
                'work_team_id' => 3,
                'name' => 'Dengan Tidak Hormat',
                'code' => 'KP.620',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 182,
                'work_team_id' => 3,
                'name' => 'Pensiun',
                'code' => 'KP.630',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 183,
                'work_team_id' => 3,
                'name' => 'Berkas Perorangan',
                'code' => 'KP.700',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 184,
                'work_team_id' => 3,
                'name' => 'Berkas Perorangan Pegawai Negeri Sipil',
                'code' => 'KP.710',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 185,
                'work_team_id' => 3,
                'name' => 'Berkas Perorangan Pejabat Negara',
                'code' => 'KP.720',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 186,
                'work_team_id' => 7,
                'name' => 'Perencanaan Kebijakan dan Laporan Pengawasan',
                'code' => 'PW.000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 187,
                'work_team_id' => 7,
                'name' => 'Perencanaan Pengawasan',
                'code' => 'PW.010',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 188,
                'work_team_id' => 7,
                'name' => 'Kerjasama Pengawasan',
                'code' => 'PW.020',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 189,
                'work_team_id' => 7,
                'name' => 'Laporan Hasil Pemeriksaan',
                'code' => 'PW.030',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 190,
                'work_team_id' => 7,
                'name' => 'Pemeriksaan (Audit)',
                'code' => 'PW.100',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 191,
                'work_team_id' => 7,
                'name' => 'Reviu RKA-KL',
                'code' => 'PW.110',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 192,
                'work_team_id' => 7,
                'name' => 'Pemeriksaan Dengan Tujuan Tertentu (PDTT) dan Pemeriksaan Khusus',
                'code' => 'PW.120',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 193,
                'work_team_id' => 7,
                'name' => 'Pemeriksaan Kinerja',
                'code' => 'PW.130',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 194,
                'work_team_id' => 7,
                'name' => 'Pemeriksaan Keuangan',
                'code' => 'PW.140',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 195,
                'work_team_id' => 7,
                'name' => 'Pemeriksaan BMN dan Hibah',
                'code' => 'PW.150',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 196,
                'work_team_id' => 7,
                'name' => 'Pemeriksaan LAKIP',
                'code' => 'PW.160',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 197,
                'work_team_id' => 7,
                'name' => 'Evaluasi',
                'code' => 'PW.170',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 198,
                'work_team_id' => 7,
                'name' => 'Pemantauan',
                'code' => 'PW.200',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 199,
                'work_team_id' => 7,
                'name' => 'Tuntutan Ganti Rugi (TGR)',
                'code' => 'PW.210',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 200,
                'work_team_id' => 7,
                'name' => 'Tindak Lanjut Laporan Hasil Pemeriksaan (TLLHP)',
                'code' => 'PW.220',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 201,
                'work_team_id' => 7,
                'name' => 'Penerapan Sistem Peringatan Dini (Early Warning System)',
                'code' => 'PW.230',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 202,
                'work_team_id' => 7,
                'name' => 'Pengawasan Masyarakat',
                'code' => 'PW.300',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 203,
                'work_team_id' => 7,
                'name' => 'Internal',
                'code' => 'PW.310',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 204,
                'work_team_id' => 7,
                'name' => 'Eksternal',
                'code' => 'PW.320',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 205,
                'work_team_id' => 7,
                'name' => 'Sistem Pengendalian Intern',
                'code' => 'PW.400',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 206,
                'work_team_id' => 7,
                'name' => 'Pembinaan Komitment Anti Korupsi',
                'code' => 'PW.410',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 207,
                'work_team_id' => 7,
                'name' => 'Penerapan Sistem Pengendalian Internal Pemerintah',
                'code' => 'PW.420',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 208,
                'work_team_id' => 7,
                'name' => 'Pengelolaan Gratifikasi',
                'code' => 'PW.430',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 209,
                'work_team_id' => 2,
                'name' => 'Kode KU lama',
                'code' => 'KU',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 210,
                'work_team_id' => 6,
                'name' => 'Kode RC lama',
                'code' => 'RC',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 211,
                'work_team_id' => 3,
                'name' => 'Kode KP lama',
                'code' => 'KP',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
