<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class WorkTeamClassificationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('work_team_classifications')->insert([         
        [
            'id' => 1,
            'name' => 'Penyusunan Kebijakan, Program dan Wilayah ',
            'code' => 'RC.000 ',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 2,
            'name' => 'Kebijakan Pembangunan Pertanian',
            'code' => 'RC.010 ',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 3,
            'name' => 'Rencana dan Program Pembangunan Pertanian',
            'code' => 'RC.020 ',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 4,
            'name' => 'Penetapan Kinerja Tahunan',
            'code' => 'RC.030 ',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 5,
            'name' => 'Pengembangan Wilayah',
            'code' => 'RC.040 ',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 6,
            'name' => 'Penyusunan Anggaran',
            'code' => 'RC.100',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 7,
            'name' => 'Penyusunan Anggaran Kantor Pusat',
            'code' => 'RC.110',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 8,
            'name' => 'Penyusunan Anggaran Dana Dekonsentrasi',
            'code' => 'RC.120',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 9,
            'name' => 'Penyusunan Anggaran Dana Tugas Pembantuan',
            'code' => 'RC.130',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 10,
            'name' => 'Penyusunan Anggaran Unit Pelaksana Teknis (UPT)',
            'code' => 'RC.140',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 11,
            'name' => 'Pemantauan dan Evaluasi Program ',
            'code' => 'RC.200',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 12,
            'name' => 'Program Bersumber dari APBN ',
            'code' => 'RC.210',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 13,
            'name' => 'Program Bersumber Dari Dana Dekonsentrasi',
            'code' => 'RC.220',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 14,
            'name' => 'Program Bersumber Dari Dana Tugas Pembantuan',
            'code' => 'RC.230',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 15,
            'name' => 'Program Bersumber Dari Dana Alokasi Khusus (DAK)',
            'code' => 'RC.240',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 16,
            'name' => 'Program Bersumber Dari Dana Public Service Obligation (PSO)',
            'code' => 'RC.250',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 17,
            'name' => 'Program Bersumber Dari Dana Kredit Program',
            'code' => 'RC.260',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 18,
            'name' => 'Program Bersumber Dari Dana Subsidi',
            'code' => 'RC.270',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 19,
            'name' => 'Program Bersumber Dari Anggaran Lainnya',
            'code' => 'RC.280',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 20,
            'name' => 'Pelaporan',
            'code' => 'RC.300',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 21,
            'name' => 'Laporan Khusus',
            'code' => 'RC.310',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 22,
            'name' => 'Laporan Berkala',
            'code' => 'RC.320',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 23,
            'name' => 'Laporan Kinerja',
            'code' => 'RC.330',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 24,
            'name' => 'Organisasi',
            'code' => 'OT.000',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 25,
            'name' => 'Organisasi Kementerian Pertanian',
            'code' => 'OT.010',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 26,
            'name' => 'Organisasi Unit Pelaksana Teknis (UPT)',
            'code' => 'OT.020',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 27,
            'name' => 'Organisasi Satuan Kerja Perangkat Daerah ( SKPD )',
            'code' => 'OT.030',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 28,
            'name' => 'Rincian Tugas Pekerjaan',
            'code' => 'OT.040',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 29,
            'name' => 'Organisasi Non Struktural',
            'code' => 'OT.050',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 30,
            'name' => 'Organisasi Non Kedinasan',
            'code' => 'OT.060',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 31,
            'name' => 'Budaya Kerja',
            'code' => 'OT.070',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 32,
            'name' => 'Pelayanan Publik',
            'code' => 'OT.080',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 33,
            'name' => 'Jabatan Fungsional',
            'code' => 'OT.100',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 34,
            'name' => 'Jabatan Fungsional Rumpun Ilmu Hayat Pertanian (RIHP)',
            'code' => 'OT.110',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 35,
            'name' => 'Jabatan Fungsional Non Rumpun Ilmu Hayat Pertanian (Non- RIHP)',
            'code' => 'OT.120',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 36,
            'name' => 'Tata Laksana',
            'code' => 'OT.200',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 37,
            'name' => 'Prosedur Kerja',
            'code' => 'OT.210',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 38,
            'name' => 'Tata Hubungan Kerja',
            'code' => 'OT.220',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 39,
            'name' => 'Pembakuan Sarana Kerja',
            'code' => 'OT.230',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 40,
            'name' => 'Reformasi Birokrasi',
            'code' => 'OT.240',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 41,
            'name' => 'Ketatausahaan',
            'code' => 'TU.000',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 42,
            'name' => 'Upacara/ Acara Kedinasan',
            'code' => 'TU.010',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 43,
            'name' => 'Rapat Pimpinan (Rapim)',
            'code' => 'TU.020',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 44,
            'name' => 'Tanda Penghargaan, Kenang-kenangan dan Ucapan',
            'code' => 'TU.030',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 45,
            'name' => 'Perjalanan Dinas Dalam Negeri',
            'code' => 'TU.040',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 46,
            'name' => 'Perjalanan Dinas Luar Negeri',
            'code' => 'TU.050',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 47,
            'name' => 'Kearsipan',
            'code' => 'TU.100',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 48,
            'name' => 'Pembinaan Kearsipan',
            'code' => 'TU.110',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 49,
            'name' => 'Tata Laksana Naskah Dinas',
            'code' => 'TU.120',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 50,
            'name' => 'Penggunaan dan Pemeliharaan',
            'code' => 'TU.130',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 51,
            'name' => 'Penyusutan',
            'code' => 'TU.140',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 52,
            'name' => 'Penggunaan dan Pemeliharaan Sarana dan Prasarana Kantor ',
            'code' => 'RT.000',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 53,
            'name' => 'Gedung dan Bangunan',
            'code' => 'RT.010',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 54,
            'name' => 'Kendaraan Dinas',
            'code' => 'RT.020',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 55,
            'name' => 'Telekomunikasi, Penerangan dan Peralatan Kantor Lainnya',
            'code' => 'RT.030',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 56,
            'name' => 'Keamanan dan ketertiban',
            'code' => 'RT.100',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 57,
            'name' => 'Pertamanan dan Kebersihan',
            'code' => 'RT.200',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 58,
            'name' => 'Pengadaan Barang',
            'code' => 'PL.000',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 59,
            'name' => 'Pengadaan Barang Bergerak',
            'code' => 'PL.010',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 60,
            'name' => 'Pengadaan Barang Tidak Bergerak',
            'code' => 'PL.020',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 61,
            'name' => 'Pengadaan Barang Tak Berwujud',
            'code' => 'PL.040',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 62,
            'name' => 'Pemindahtanganan',
            'code' => 'PL.100',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 63,
            'name' => 'Penjualan',
            'code' => 'PL.110',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 64,
            'name' => 'Tukar Menukar',
            'code' => 'PL.120',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 65,
            'name' => 'Hibah',
            'code' => 'PL.130',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 66,
            'name' => 'Penyertaan Modal Pemerintah',
            'code' => 'PL.140',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 67,
            'name' => 'Penatausahaan',
            'code' => 'PL.200',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 68,
            'name' => 'Pembukuan',
            'code' => 'PL.210',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 69,
            'name' => 'Inventarisasi Penilaian',
            'code' => 'PL.220',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 70,
            'name' => 'Laporan BMN',
            'code' => 'PL.230',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 71,
            'name' => 'Pemanfaatan, Penghapusan, Pengawasan, Pengendalian BMN',
            'code' => 'PL.300',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 72,
            'name' => 'Pemanfaatan',
            'code' => 'PL.310',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 73,
            'name' => 'Penghapusan',
            'code' => 'PL.320',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 74,
            'name' => 'Pengawasan dan Pengendalian',
            'code' => 'PL.330',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 75,
            'name' => 'Program Legislasi Pertanian',
            'code' => 'HK.000',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 76,
            'name' => 'Peraturan Perundang-undangan',
            'code' => 'HK.100',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 77,
            'name' => 'Undang-Undang atau Peraturan Pemerintah Pengganti Undang-undang dalam Bidang Pertanian',
            'code' => 'HK.110',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 78,
            'name' => 'Peraturan Pemerintah dalam Bidang Pertanian',
            'code' => 'HK.120',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 79,
            'name' => 'Peraturan/Keputusan/Instruksi Presiden dalam Bidang Pertanian',
            'code' => 'HK.130',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 80,
            'name' => 'Peraturan Menteri Pertanian',
            'code' => 'HK.140',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 81,
            'name' => 'Keputusan/ Instruksi Menteri Pertanian',
            'code' => 'HK.150',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 82,
            'name' => 'Keputusan/ Instruksi Pimpinan Unit Kerja',
            'code' => 'HK.160',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 83,
            'name' => 'Perjanjian',
            'code' => 'HK.200',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 84,
            'name' => 'Kesepakatan Bersama',
            'code' => 'HK.210',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 85,
            'name' => 'Nota  kesepahaman/  Memorandum  of  Understanding (MoU)',
            'code' => 'HK.220',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 86,
            'name' => 'Perjanjian Kerjasama',
            'code' => 'HK.230',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 87,
            'name' => 'Pembinaan dan Dokumentasi Hukum',
            'code' => 'HK.300',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 88,
            'name' => 'Pembinaan Hukum',
            'code' => 'HK.310',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 89,
            'name' => 'Dokumentasi Hukum',
            'code' => 'HK.320',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 90,
            'name' => 'Bantuan/Konsultasi/Advokasi Hukum',
            'code' => 'HK.400',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 91,
            'name' => 'Perdata',
            'code' => 'HK.410',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 92,
            'name' => 'Tata Usaha Negara',
            'code' => 'HK.420',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 93,
            'name' => 'Pengujian Materiil (Judicial Review)',
            'code' => 'HK.430',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 94,
            'name' => 'Hak Atas Kekayaan Intelektual (HaKI)',
            'code' => 'HK.500',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 95,
            'name' => 'Hak Cipta',
            'code' => 'HK.510',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 96,
            'name' => 'Hak Paten',
            'code' => 'HK.520',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 97,
            'name' => 'Hak Merk',
            'code' => 'HK.530',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 98,
            'name' => 'Varietas Tanaman',
            'code' => 'HK.540',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 99,
            'name' => 'Hak Desain Industri',
            'code' => 'HK.550',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 100,
            'name' => 'Rahasia Dagang',
            'code' => 'HK.560',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 101,
            'name' => 'Desain Tata Letak Sirkuit Terpadu',
            'code' => 'HK.570',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 102,
            'name' => 'Kerjasama Bilateral',
            'code' => 'KL.000',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 103,
            'name' => 'Asia Pasifik',
            'code' => 'KL.010',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 104,
            'name' => 'Amerika',
            'code' => 'KL.020',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 105,
            'name' => 'Eropa',
            'code' => 'KL.030',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 106,
            'name' => 'Afrika',
            'code' => 'KL.040',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 107,
            'name' => 'Timur Tengah',
            'code' => 'KL.050',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 108,
            'name' => 'Kerjasama Regional',
            'code' => 'KL.100',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 109,
            'name' => 'ASEAN',
            'code' => 'KL.110',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 110,
            'name' => 'NON- ASEAN',
            'code' => 'KL.120',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 111,
            'name' => 'Intra Kawasan',
            'code' => 'KL.130',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 112,
            'name' => 'Kerjasama Multilateral',
            'code' => 'KL.200',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 113,
            'name' => 'PBB',
            'code' => 'KL.210',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 114,
            'name' => 'Organisasi Internasional Pemerintah dan Non Pemerintah',
            'code' => 'KL.220',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 115,
            'name' => 'Administrasi Perencanaan',
            'code' => 'KL.230',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 116,
            'name' => 'Keprotokolan',
            'code' => 'HM.000',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 117,
            'name' => 'Agenda Pimpinan',
            'code' => 'HM.010',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 118,
            'name' => 'Kunjungan',
            'code' => 'HM.020',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 119,
            'name' => 'Dokumentasi dan Penyajian Informasi Kelembagaan',
            'code' => 'HM.100',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 120,
            'name' => 'Dokumentasi',
            'code' => 'HM.110',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 121,
            'name' => 'Publikasi',
            'code' => 'HM.120',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 122,
            'name' => 'Informasi Publik',
            'code' => 'HM.130',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 123,
            'name' => 'Penerbitan',
            'code' => 'HM.140',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 124,
            'name' => 'Pameran',
            'code' => 'HM.150',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 125,
            'name' => 'Pers/ Media Massa',
            'code' => 'HM.160',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 126,
            'name' => 'Pendapat umum',
            'code' => 'HM.170',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 127,
            'name' => 'Bahan/Materi Pidato Pimpinan',
            'code' => 'HM.180',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 128,
            'name' => 'Perpustakaan',
            'code' => 'HM.190',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 129,
            'name' => 'Hubungan Antar Lembaga',
            'code' => 'HM.200',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 130,
            'name' => 'Lembaga Tertinggi Dan Tinggi Negara',
            'code' => 'HM.210',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 131,
            'name' => 'Lembaga Pemerintah',
            'code' => 'HM.210',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 132,
            'name' => 'Organisasi Sosial/ LSM',
            'code' => 'HM.220',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 133,
            'name' => 'Perusahaan',
            'code' => 'HM.230',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 134,
            'name' => 'Perguruan Tinggi/ Sekolah',
            'code' => 'HM.240',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 135,
            'name' => 'Asosiasi/ Organisasi Profesi',
            'code' => 'HM.250',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 136,
            'name' => 'Badan Koordinasi Kehumasan (Bakohumas)',
            'code' => 'HM.260',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 137,
            'name' => 'Pelaksanaan Anggaran',
            'code' => 'KU.000',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 138,
            'name' => 'Pejabat Pengelola Keuangan',
            'code' => 'KU.010',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 139,
            'name' => 'Pendapatan',
            'code' => 'KU.020',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 140,
            'name' => 'Penerimaan Negara Bukan Pajak (PNBP)',
            'code' => 'KU.030',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 141,
            'name' => 'Belanja',
            'code' => 'KU.040',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 142,
            'name' => 'Pembukuan Keuangan',
            'code' => 'KU.050',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 143,
            'name' => 'Penggajian dan Tunjangan',
            'code' => 'KU.060',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 144,
            'name' => 'Rekening Pemerintah',
            'code' => 'KU.070',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 145,
            'name' => 'Laporan Keuangan',
            'code' => 'KU.100',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 146,
            'name' => 'Laporan Keuangan Bulanan',
            'code' => 'KU.110',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 147,
            'name' => 'Laporan Keuangan Triwulanan',
            'code' => 'KU.120',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 148,
            'name' => 'Laporan Keuangan Semesteran',
            'code' => 'KU.130',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 149,
            'name' => 'Laporan Keuangan Tahunan',
            'code' => 'KU.140',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 150,
            'name' => 'Bantuan/ Pinjaman Luar Negeri',
            'code' => 'KU.200',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 151,
            'name' => 'Pertanggungjawaban Keuangan Negara',
            'code' => 'KU.300',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 152,
            'name' => 'Laporan Hasil Pemeriksaan',
            'code' => 'KU.310',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 153,
            'name' => 'Dokumen Penyelesaian Keuangan Negara',
            'code' => 'KU.320',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 154,
            'name' => 'Perencanaan Kebutuhan Pegawai',
            'code' => 'KP.000',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 155,
            'name' => 'Analisis Jabatan/ Beban Kerja',
            'code' => 'KP.010',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 156,
            'name' => 'Formasi',
            'code' => 'KP.020',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 157,
            'name' => 'Data Pegawai',
            'code' => 'KP.030',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 158,
            'name' => 'Pengadaan Pegawai',
            'code' => 'KP.100',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 159,
            'name' => 'Penerimaan Pegawai',
            'code' => 'KP.110',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 160,
            'name' => 'Pengangkatan CPNS',
            'code' => 'KP.120',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 161,
            'name' => 'Pengangkatan PNS',
            'code' => 'KP.130',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 162,
            'name' => 'Pengangkatan dan Kepangkatan',
            'code' => 'KP.200',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 163,
            'name' => 'Kenaikan Pangkat Jabatan Struktural',
            'code' => 'KP.210',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 164,
            'name' => 'Kenaikan Pangkat Jabatan Fungsional',
            'code' => 'KP.220',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 165,
            'name' => 'Pengangkatan dan Pemberhentian dalam Jabatan Struktural',
            'code' => 'KP.230',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 166,
            'name' => 'Pengangkatan dan Pemberhentian dalam Jabatan Fungsional',
            'code' => 'KP.240',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 167,
            'name' => 'Alih Tugas',
            'code' => 'KP.250',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 168,
            'name' => 'Mutasi Keluarga',
            'code' => 'KP.260',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 169,
            'name' => 'Peninjauan Masa Kerja',
            'code' => 'KP.270',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 170,
            'name' => 'Penetapan Perubahan Data Dasar/ Status/ Kedudukan Hukum Pegawai',
            'code' => 'KP.280',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 171,
            'name' => 'Baperjakat',
            'code' => 'KP.290',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 172,
            'name' => 'Pembinaan Karier Pegawai',
            'code' => 'KP.300',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 173,
            'name' => 'Diklat/Kursus/Ujian Dinas/Ujian Kenaikan Pangkat Penyesuaian Ijazah Pegawai',
            'code' => 'KP.310',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 174,
            'name' => 'Tugas Belajar',
            'code' => 'KP.320',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 175,
            'name' => 'Izin Belajar Pegawai',
            'code' => 'KP.330',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 176,
            'name' => 'Penilaian Kinerja Pegawai',
            'code' => 'KP.340',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 177,
            'name' => 'Kompetensi Pegawai',
            'code' => 'KP.350',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 178,
            'name' => 'Perselisihan/ Sengketa Kepegawaian',
            'code' => 'KP.360',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 179,
            'name' => 'Disiplin Pegawai',
            'code' => 'KP.370',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 180,
            'name' => 'Administrasi Pegawai',
            'code' => 'KP.400',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 181,
            'name' => 'Pelaksana Tugas/Harian',
            'code' => 'KP.410',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 182,
            'name' => 'Kartu Identitas Pegawai',
            'code' => 'KP.420',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 183,
            'name' => 'Keterangan Pegawai',
            'code' => 'KP.430',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 184,
            'name' => 'Kesejahteraan Pegawai',
            'code' => 'KP.500',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 185,
            'name' => 'Pemeliharaan Kesehatan Pegawai',
            'code' => 'KP.510',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 186,
            'name' => 'Tabungan Pensiun (Taspen)',
            'code' => 'KP.520',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 187,
            'name' => 'Tabungan Perumahan (Bapetarum)',
            'code' => 'KP.530',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 188,
            'name' => 'Dana Sosial',
            'code' => 'KP.540',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 189,
            'name' => 'Pakaian Dinas',
            'code' => 'KP.550',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 190,
            'name' => 'Pengurusan Jenazah',
            'code' => 'KP.560',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 191,
            'name' => 'Olahraga dan Rekreasi',
            'code' => 'KP.570',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 192,
            'name' => 'Cuti',
            'code' => 'KP.580',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 193,
            'name' => 'Penghargaan dan Tanda Jasa',
            'code' => 'KP.590',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 194,
            'name' => 'Pemberhentian Pegawai',
            'code' => 'KP.600',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 195,
            'name' => 'Dengan Hormat',
            'code' => 'KP.610',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 196,
            'name' => 'Dengan Tidak Hormat',
            'code' => 'KP.620',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 197,
            'name' => 'Pensiun',
            'code' => 'KP.630',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 198,
            'name' => 'Berkas Perorangan',
            'code' => 'KP.700',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 199,
            'name' => 'Berkas Perorangan Pegawai Negeri Sipil',
            'code' => 'KP.710',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 200,
            'name' => 'Berkas Perorangan Pejabat Negara',
            'code' => 'KP.720',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 201,
            'name' => 'Perencanaan Kebijakan dan Laporan Pengawasan',
            'code' => 'PW.000',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 202,
            'name' => 'Perencanaan Pengawasan',
            'code' => 'PW.010',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 203,
            'name' => 'Kerjasama Pengawasan',
            'code' => 'PW.020',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 204,
            'name' => 'Laporan Hasil Pemeriksaan',
            'code' => 'PW.030',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 205,
            'name' => 'Pemeriksaan (Audit)',
            'code' => 'PW.100',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 206,
            'name' => 'Reviu RKA-KL',
            'code' => 'PW.110',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 207,
            'name' => 'Pemeriksaan Dengan Tujuan Tertentu (PDTT) dan Pemeriksaan Khusus',
            'code' => 'PW.120',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 208,
            'name' => 'Pemeriksaan Kinerja',
            'code' => 'PW.130',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 209,
            'name' => 'Pemeriksaan Keuangan',
            'code' => 'PW.140',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 210,
            'name' => 'Pemeriksaan BMN dan Hibah',
            'code' => 'PW.150',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 211,
            'name' => 'Pemeriksaan LAKIP',
            'code' => 'PW.160',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 212,
            'name' => 'Evaluasi',
            'code' => 'PW.170',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 213,
            'name' => 'Pemantauan',
            'code' => 'PW.200',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 214,
            'name' => 'Tuntutan Ganti Rugi (TGR)',
            'code' => 'PW.210',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 215,
            'name' => 'Tindak Lanjut Laporan Hasil Pemeriksaan (TLLHP)',
            'code' => 'PW.220',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 216,
            'name' => 'Penerapan Sistem Peringatan Dini (Early Warning System)',
            'code' => 'PW.230',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 217,
            'name' => 'Pengawasan Masyarakat',
            'code' => 'PW.300',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 218,
            'name' => 'Internal',
            'code' => 'PW.310',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 219,
            'name' => 'Eksternal',
            'code' => 'PW.320',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 220,
            'name' => 'Sistem Pengendalian Intern',
            'code' => 'PW.400',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 221,
            'name' => 'Pembinaan Komitment Anti Korupsi',
            'code' => 'PW.410',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 222,
            'name' => 'Penerapan Sistem Pengendalian Internal Pemerintah',
            'code' => 'PW.420',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 223,
            'name' => 'Pengelolaan Gratifikasi',
            'code' => 'PW.430',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 224,
            'name' => 'Data dan Informasi Komoditas Pertanian ',
            'code' => 'TI.000',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 225,
            'name' => 'Tanaman Pangan',
            'code' => 'TI.010',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 226,
            'name' => 'Hortikultura',
            'code' => 'TI.020',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 227,
            'name' => 'Perkebunan',
            'code' => 'TI.030',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 228,
            'name' => 'Peternakan dan Kesehatan Hewan',
            'code' => 'TI.040',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 229,
            'name' => 'Sarana dan Prasarana Pertanian',
            'code' => 'TI.050',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 230,
            'name' => 'Sosial Ekonomi Pertanian',
            'code' => 'TI.060',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 231,
            'name' => 'Sistem Informasi',
            'code' => 'TI.100',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 232,
            'name' => 'Sistem Jaringan Komputer',
            'code' => 'TI.110',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 233,
            'name' => 'Aplikasi Sistem Informasi',
            'code' => 'TI.120',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 234,
            'name' => 'Aplikasi Multimedia dan Website',
            'code' => 'TI.130',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 235,
            'name' => 'Perluasan dan Pengelolaan Lahan',
            'code' => 'SR.000',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 236,
            'name' => 'Basis Data Lahan',
            'code' => 'SR.010',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 237,
            'name' => 'Pengendalian Lahan',
            'code' => 'SR.020',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 238,
            'name' => 'Optimasi, Rehabilitasi dan Konservasi Lahan',
            'code' => 'SR.030',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 239,
            'name' => 'Perluasan Kawasan',
            'code' => 'SR.040',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 240,
            'name' => 'Pengelolaan Air Irigasi',
            'code' => 'SR.100',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 241,
            'name' => 'Pengembangan Sumber Air',
            'code' => 'SR.110',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 242,
            'name' => 'Pengembangan Jaringan Air',
            'code' => 'SR.120',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 243,
            'name' => 'Optimasi Air',
            'code' => 'SR.130',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 244,
            'name' => 'Iklim',
            'code' => 'SR.140',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 245,
            'name' => 'Konservasi Air dan Lingkungan Hidup',
            'code' => 'SR.150',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 246,
            'name' => 'Kelembagaan Pengelolaan Air',
            'code' => 'SR.160',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 247,
            'name' => 'Pembiayaan Pertanian',
            'code' => 'SR.200',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 248,
            'name' => 'Pembiayaan Program',
            'code' => 'SR.210',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 249,
            'name' => 'Pembiayaan syariah',
            'code' => 'SR.220',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 250,
            'name' => 'Pembiayaan Agribisnis',
            'code' => 'SR.230',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 251,
            'name' => 'Pemberdayaan Agribisnis',
            'code' => 'SR.240',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 252,
            'name' => 'Kelembagaan  Agribisnis',
            'code' => 'SR.250',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 253,
            'name' => 'Pupuk dan Pestisida',
            'code' => 'SR.300',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 254,
            'name' => 'Pupuk Organik dan Pembenah Tanah',
            'code' => 'SR.310',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 255,
            'name' => 'Pupuk Anorganik',
            'code' => 'SR.320',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 256,
            'name' => 'Pestisida',
            'code' => 'SR.330',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 257,
            'name' => 'Pengawasan Pupuk',
            'code' => 'SR.340',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 258,
            'name' => 'Pengawasan Pestisida',
            'code' => 'SR.350',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 259,
            'name' => 'Alat dan Mesin Pertanian',
            'code' => 'SR.400',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 260,
            'name' => 'Pengembangan Alat dan Mesin Pertanian',
            'code' => 'SR.410',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 261,
            'name' => 'Pengawasan dan Peredaran Alat dan Mesin Pertanian',
            'code' => 'SR.420',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 262,
            'name' => 'Pelayanan Alat dan Mesin Pertanian',
            'code' => 'SR.430',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 263,
            'name' => 'Kelembagaan Alat dan Mesin Pertanian',
            'code' => 'SR.440',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 264,
            'name' => 'Perbenihan Tanaman Pangan',
            'code' => 'TP.000',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 265,
            'name' => 'Penilaian Varietas',
            'code' => 'TP.010',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 266,
            'name' => 'Pengawasan Mutu Benih',
            'code' => 'TP.020',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 267,
            'name' => 'Produksi Benih ',
            'code' => 'TP.030',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 268,
            'name' => 'Produksi Benih Aneka Kacang',
            'code' => 'TP.040',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 269,
            'name' => 'Produksi Benih Aneka Umbi',
            'code' => 'TP.050',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 270,
            'name' => 'Kelembagaan Benih',
            'code' => 'TP.060',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 271,
            'name' => 'Budidaya Serealia',
            'code' => 'TP.100',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 272,
            'name' => 'Padi Irigasi',
            'code' => 'TP.110',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 273,
            'name' => 'Padi Rawa',
            'code' => 'TP.120',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 274,
            'name' => 'Padi Tadah Hujan',
            'code' => 'TP.130',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 275,
            'name' => 'Padi Lahan Kering',
            'code' => 'TP.140',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 276,
            'name' => 'Intensifikasi dan pengembangan Jagung',
            'code' => 'TP.150',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 277,
            'name' => 'Intensifikasi dan pengembangan Serealia Lain',
            'code' => 'TP.160',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 278,
            'name' => 'Budidaya Aneka kacang dan umbi',
            'code' => 'TP.200',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 279,
            'name' => 'Kedelai  ',
            'code' => 'TP.210',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 280,
            'name' => 'Ubi Kayu  ',
            'code' => 'TP.220',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 281,
            'name' => 'Aneka Kacang  ',
            'code' => 'TP.230',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 282,
            'name' => 'Aneka Umbi  ',
            'code' => 'TP.240',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 283,
            'name' => 'Perlindungan Tanaman Pangan',
            'code' => 'TP.300',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 284,
            'name' => 'Organisme Pengganggu Tumbuhan ',
            'code' => 'TP.310',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 285,
            'name' => 'Dampak Perubahan Iklim',
            'code' => 'TP.320',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 286,
            'name' => 'Pengendalian Hama Terpadu',
            'code' => 'TP.330',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 287,
            'name' => 'Pascapanen Tanaman Pangan',
            'code' => 'TP.400',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 288,
            'name' => 'Teknologi Pasca Panen Tanaman Pangan',
            'code' => 'TP.410',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 289,
            'name' => 'Sarana Pasca Panen Tanaman Pangan',
            'code' => 'TP.410',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 290,
            'name' => 'Perbenihan Hortikultura',
            'code' => 'HR.000',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 291,
            'name' => 'Perbenihan Tanaman Buah',
            'code' => 'HR.010',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 292,
            'name' => 'Perbenihan Tanaman Sayuran',
            'code' => 'HR.020',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 293,
            'name' => 'Perbenihan Tanaman Obat',
            'code' => 'HR.030',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 294,
            'name' => 'Perbenihan Tanaman Florikultura',
            'code' => 'HR.040',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 295,
            'name' => 'Penilaian Varietas',
            'code' => 'HR.050',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 296,
            'name' => 'Pengawasan Mutu Benih',
            'code' => 'HR.060',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 297,
            'name' => 'Teknologi Budidaya',
            'code' => 'HR.100 ',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 298,
            'name' => 'Tanaman Buah',
            'code' => 'HR.110',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 299,
            'name' => 'Tanaman Sayur',
            'code' => 'HR.120',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 300,
            'name' => 'Tanaman Obat',
            'code' => 'HR.130',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 301,
            'name' => 'Tanaman Florikultura',
            'code' => 'HR.140',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 302,
            'name' => 'Bimbingan Usaha Budidaya',
            'code' => 'HR.200',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 303,
            'name' => 'Tanaman Buah',
            'code' => 'HR.210',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 304,
            'name' => 'Tanaman Sayur',
            'code' => 'HR.220',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 305,
            'name' => 'Tanaman Obat',
            'code' => 'HR.230',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 306,
            'name' => 'Tanaman Florikultura',
            'code' => 'HR.240',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 307,
            'name' => 'Teknologi Pascapanen',
            'code' => 'HR.300',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 308,
            'name' => 'Tanaman Buah',
            'code' => 'HR.310',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 309,
            'name' => 'Tanaman Sayur',
            'code' => 'HR.320',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 310,
            'name' => 'Tanaman Obat',
            'code' => 'HR.330',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 311,
            'name' => 'Tanaman Florikultura',
            'code' => 'HR.340',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 312,
            'name' => 'Sarana Pascapanen',
            'code' => 'HR.400',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 313,
            'name' => 'Tanaman Buah',
            'code' => 'HR.410',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 314,
            'name' => 'Tanaman Sayur',
            'code' => 'HR.420',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 315,
            'name' => 'Tanaman Obat',
            'code' => 'HR.430',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 316,
            'name' => 'Tanaman Florikultura',
            'code' => 'HR.440',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 317,
            'name' => 'Teknologi Perlindungan Hortikultura',
            'code' => 'HR.500',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 318,
            'name' => 'Tanaman buah',
            'code' => 'HR.510',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 319,
            'name' => 'Tanaman Sayuran',
            'code' => 'HR.520',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 320,
            'name' => 'Tanaman Obat.',
            'code' => 'HR.530',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 321,
            'name' => 'Tanaman Florikultura',
            'code' => 'HR.540',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 322,
            'name' => 'Pengendalian Organisme Pengganggu Tumbuhan Hortikultura',
            'code' => 'HR.600',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 323,
            'name' => 'Tanaman Buah',
            'code' => 'HR.610',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 324,
            'name' => 'Tanaman Sayuran',
            'code' => 'HR.620',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 325,
            'name' => 'Tanaman Obat.',
            'code' => 'HR.630',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 326,
            'name' => 'Tanaman Florikultura',
            'code' => 'HR.640',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 327,
            'name' => 'Dampak Perubahan Iklim',
            'code' => 'HR.700 ',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 328,
            'name' => 'Dampak iklim dan Persyaratan Teknis',
            'code' => 'HR.710',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 329,
            'name' => 'Pengolahan Hasil Pertanian',
            'code' => 'PP.000',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 330,
            'name' => 'Tanaman Pangan',
            'code' => 'PP.010',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 331,
            'name' => 'Hortikultura',
            'code' => 'PP.020',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 332,
            'name' => 'Perkebunan',
            'code' => 'PP.030',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 333,
            'name' => 'Peternakan',
            'code' => 'PP.040',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 334,
            'name' => 'Mutu dan Standarisasi',
            'code' => 'PP.100',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 335,
            'name' => 'Standardisasi Tanaman Pangan dan Hortikultura',
            'code' => 'PP.110',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 336,
            'name' => 'Standardisasi Perkebunan dan Peternakan',
            'code' => 'PP.120',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 337,
            'name' => 'Penerapan dan Pengawasan Jaminan Mutu',
            'code' => 'PP.130',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 338,
            'name' => 'Akreditasi dan Kelembagaan',
            'code' => 'PP.140',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 339,
            'name' => 'Kerjasama dan Harmonisasi',
            'code' => 'PP.150',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 340,
            'name' => 'Pengembangan Usaha dan Investasi',
            'code' => 'PP.200',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 341,
            'name' => 'Kemitraan dan Kewirausahaan',
            'code' => 'PP.210',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 342,
            'name' => 'Investasi',
            'code' => 'PP.220',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 343,
            'name' => 'Promosi Dalam Negeri dan Luar Negeri',
            'code' => 'PP.230',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 344,
            'name' => 'Pemasaran Domestik',
            'code' => 'PP.300',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 345,
            'name' => 'Informasi Pasar',
            'code' => 'PP.310',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 346,
            'name' => 'Pemantauan Pasar dan Stabilisasi Harga',
            'code' => 'PP.320',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 347,
            'name' => 'Sarana dan Kelembagaan Pasar',
            'code' => 'PP.330',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 348,
            'name' => 'Jaringan Pemasaran',
            'code' => 'PP.340',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 349,
            'name' => 'Pemasaran Internasional',
            'code' => 'PP.400',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 350,
            'name' => 'Analisis dan Pengembangan Ekspor',
            'code' => 'PP.410',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 351,
            'name' => 'Pemasaran Bilateral',
            'code' => 'PP.420',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 352,
            'name' => 'Pemasaran Regional dan Multilateral',
            'code' => 'PP.430',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 353,
            'name' => 'Kerjasama Komoditi',
            'code' => 'PP.440',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 354,
            'name' => 'Perbenihan',
            'code' => 'KB.000',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 355,
            'name' => 'Penilaian Varietas dan Pengawasan Mutu Benih',
            'code' => 'KB.010',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 356,
            'name' => 'Produksi Benih',
            'code' => 'KB.020',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 357,
            'name' => 'Kelembagaan Benih',
            'code' => 'KB.030',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 358,
            'name' => 'Budidaya Perkebunan',
            'code' => 'KB.100',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 359,
            'name' => 'Tanaman Semusim',
            'code' => 'KB.110',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 360,
            'name' => 'Tanaman Tahunan',
            'code' => 'KB.120',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 361,
            'name' => 'Tanaman Rempah dan Penyegar',
            'code' => 'KB.130',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 362,
            'name' => 'Perlindungan Perkebunan',
            'code' => 'KB.200',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 363,
            'name' => 'Organisme Pengganggu Tumbuhan',
            'code' => 'KB.210',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 364,
            'name' => 'Iklim dan Pencegahan Kebakaran',
            'code' => 'KB.220',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 365,
            'name' => 'Pascapanen Perkebunan',
            'code' => 'KB.300',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 366,
            'name' => 'Tanaman Semusim',
            'code' => 'KB.310',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 367,
            'name' => 'Tanaman Rempah dan Penyegar',
            'code' => 'KB.320',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 368,
            'name' => 'Tanaman Tahunan',
            'code' => 'KB.330',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 369,
            'name' => 'Pembinaan Usaha',
            'code' => 'KB.400',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 370,
            'name' => 'Bimbingan Usaha dan Perkebunan Berkelanjutan',
            'code' => 'KB.410',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 371,
            'name' => 'Gangguan Usaha dan Penanganan Konflik',
            'code' => 'KB.420',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 372,
            'name' => 'Perbibitan Ternak',
            'code' => 'PK.000',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 373,
            'name' => 'Produksi Bibit Ternak',
            'code' => 'PK.010',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 374,
            'name' => 'Penilaian dan Pelepasan Bibit Ternak',
            'code' => 'PK.020',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 375,
            'name' => 'Mutu Bibit ternak',
            'code' => 'PK.030',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 376,
            'name' => 'Pengembangan Bibit Ternak',
            'code' => 'PK.040',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 377,
            'name' => 'Pakan Ternak',
            'code' => 'PK.100',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 378,
            'name' => 'Bahan Pakan',
            'code' => 'PK.110',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 379,
            'name' => 'Pakan Hijauan',
            'code' => 'PK.120',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 380,
            'name' => 'Pakan Olahan',
            'code' => 'PK.130',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 381,
            'name' => 'Mutu Pakan',
            'code' => 'PK.140',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 382,
            'name' => 'Budidaya Ternak',
            'code' => 'PK.200',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 383,
            'name' => 'Ternak Potong',
            'code' => 'PK.210',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 384,
            'name' => 'Ternak Perah',
            'code' => 'PK.220',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 385,
            'name' => 'Ternak Unggas dan Aneka Ternak',
            'code' => 'PK.230',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 386,
            'name' => 'Usaha dan Kelembagaan',
            'code' => 'PK.240',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 387,
            'name' => 'Kesehatan Hewan',
            'code' => 'PK.300',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 388,
            'name' => 'Pengamatan Penyakit',
            'code' => 'PK.310',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 389,
            'name' => 'Pencegahan dan Pemberantasan Penyakit Hewan',
            'code' => 'PK.320',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 390,
            'name' => 'Perlindungan Hewan',
            'code' => 'PK.330',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 391,
            'name' => 'Kelembagaan dan Sumberdaya Kesehatan Hewan',
            'code' => 'PK.340',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 392,
            'name' => 'Pengawasan Obat Hewan',
            'code' => 'PK.350',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 393,
            'name' => 'Kesehatan Masyarakat Veteriner',
            'code' => 'PK.400',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 394,
            'name' => 'Higiene Sanitasi',
            'code' => 'PK.410',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 395,
            'name' => 'Pengawasan Sanitary dan Keamanan Produk Hewan',
            'code' => 'PK.420',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 396,
            'name' => 'Zoonosis dan Kesejahteraan Hewan',
            'code' => 'PK.430',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 397,
            'name' => 'Pengujian dan Sertifikasi Produk Hewan',
            'code' => 'PK.440',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 398,
            'name' => 'Pascapanen Hewan Ternak',
            'code' => 'PK.450',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 399,
            'name' => 'Penelitian dan Pengembangan',
            'code' => 'LB.000',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 400,
            'name' => 'Tanaman Pangan',
            'code' => 'LB.010',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 401,
            'name' => 'Hortikultura',
            'code' => 'LB.020',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 402,
            'name' => 'Perkebunan',
            'code' => 'LB.030',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 403,
            'name' => 'Peternakan dan Kesehatan Hewan',
            'code' => 'LB.040',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 404,
            'name' => 'Sosial Ekonomi dan Kebijakan pertanian',
            'code' => 'LB.050',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 405,
            'name' => 'Sumberdaya lahan pertanian',
            'code' => 'LB.060',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 406,
            'name' => 'Bioteknologi',
            'code' => 'LB.070',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 407,
            'name' => 'Mekanisasi Pertanian',
            'code' => 'LB.080',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 408,
            'name' => 'Pascapanen Pertanian',
            'code' => 'LB.090',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 409,
            'name' => 'Pengkajian Teknologi Spesifik Lokasi',
            'code' => 'LB.100',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 410,
            'name' => 'Pengelolaan alih teknologi',
            'code' => 'LB.200',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 411,
            'name' => 'Publikasi dan Diseminasi Hasil Penelitian',
            'code' => 'LB.300',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 412,
            'name' => 'Permohonan Hak Perlindungan Varietas Tanaman',
            'code' => 'PV.100',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 413,
            'name' => 'Permohonan Hak Perlindungan Varietas Tanaman (PVT)',
            'code' => 'PV.110',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 414,
            'name' => 'Pengujian Perlindungan Varietas Tanaman',
            'code' => 'PV.120',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 415,
            'name' => 'Pemberian dan Penolakan Hak Perlindungan Varietas Tanaman',
            'code' => 'PV.130',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 416,
            'name' => 'Pendaftaran Varietas Tanaman dan Sumberdaya Genetik Tanaman',
            'code' => 'PV.200',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 417,
            'name' => 'Pendaftaran Varietas Lokal',
            'code' => 'PV.210',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 418,
            'name' => 'Pendaftaran Varietas Hasil Pemuliaan',
            'code' => 'PV.220',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 419,
            'name' => 'Pendaftaran Sumberdaya Genetik Tanaman',
            'code' => 'PV.230',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 420,
            'name' => 'Pendaftaran Varietas Hortikultura',
            'code' => 'PV.240',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 421,
            'name' => 'Pestisida/obat-obatan pertanian',
            'code' => 'PI.000',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 422,
            'name' => 'Pupuk',
            'code' => 'PI.100',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 423,
            'name' => 'Tanaman Pangan',
            'code' => 'PI.200',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 424,
            'name' => 'Hortikultura',
            'code' => 'PI.300',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 425,
            'name' => 'Perkebunan',
            'code' => 'PI.400',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 426,
            'name' => 'Peternakan',
            'code' => 'PI.500',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 427,
            'name' => 'Penelitian dan Pengembangan',
            'code' => 'PI.600',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 428,
            'name' => 'Alat dan Mesin Pertanian',
            'code' => 'PI.700',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 429,
            'name' => 'Benih Tanaman dan Sumber Daya Genetik (SDG) Tanaman',
            'code' => 'PI.800',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 430,
            'name' => 'Karantina Tumbuhan dan Keamanan Hayati Nabati',
            'code' => 'KR.000',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 431,
            'name' => 'Penyakit Tumbuhan',
            'code' => 'KR.010',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 432,
            'name' => 'Tindakan Karantina Tumbuhan',
            'code' => 'KR.020',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 433,
            'name' => 'Sertifikasi Pelepasan Karantina Tumbuhan',
            'code' => 'KR.030',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 434,
            'name' => 'Keamanan Hayati Nabati',
            'code' => 'KR.040',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 435,
            'name' => 'Tertib Operasional Karantina Tumbuhan',
            'code' => 'KR.050',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 436,
            'name' => 'Karantina Hewan dan Keamanan Hayati Hewani',
            'code' => 'KR.100',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 437,
            'name' => 'Penyakit Hewan',
            'code' => 'KR.110',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 438,
            'name' => 'Tindakan Karantina Hewan',
            'code' => 'KR.120',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 439,
            'name' => 'Sertifikasi Pelepasan Karantina Hewan',
            'code' => 'KR.130',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 440,
            'name' => 'Keamanan Hayati Hewani',
            'code' => 'KR.140',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 441,
            'name' => 'Tertib Operasional Karantina Hewan',
            'code' => 'KR.150',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 442,
            'name' => 'Ketersediaan dan Kerawanan Pangan',
            'code' => 'KN.000',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 443,
            'name' => 'Ketersediaan Pangan',
            'code' => 'KN.010',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 444,
            'name' => 'Akses Pangan',
            'code' => 'KN.020',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 445,
            'name' => 'Kerawanan Pangan',
            'code' => 'KN.030',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 446,
            'name' => 'Distribusi dan Cadangan Pangan',
            'code' => 'KN.100',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 447,
            'name' => 'Distribusi Pangan',
            'code' => 'KN.110',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 448,
            'name' => 'Harga Pangan',
            'code' => 'KN.120',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 449,
            'name' => 'Cadangan Pangan',
            'code' => 'KN.130',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 450,
            'name' => 'Penganekaragaman Konsumsi dan Keamanan Pangan',
            'code' => 'KN.200',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 451,
            'name' => 'Konsumsi Pangan',
            'code' => 'KN.210',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 452,
            'name' => 'Penganekaragaman Pangan',
            'code' => 'KN.220',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 453,
            'name' => 'Keamanan Pangan Segar',
            'code' => 'KN.230',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 454,
            'name' => 'Penguatan Kelembagaan Ketahanan Pangan',
            'code' => 'KN.300',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 455,
            'name' => 'Pengelolaan Lembaga Ketahanan Pangan',
            'code' => 'KN.310',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 456,
            'name' => 'Dewan Ketahanan Pangan',
            'code' => 'KN.320',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 457,
            'name' => 'Program Peningkatan Kesejahteraan Petani Kecil',
            'code' => 'KN.330',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 458,
            'name' => 'Penghargaan Ketahanan Pangan',
            'code' => 'KN.340',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 459,
            'name' => 'Penyuluhan Pertanian',
            'code' => 'SM.000',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 460,
            'name' => 'Program dan Kerjasama',
            'code' => 'SM.010',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 461,
            'name' => 'Informasi dan Materi',
            'code' => 'SM.020',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 462,
            'name' => 'Kelembagaan Penyuluhan',
            'code' => 'SM.030',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 463,
            'name' => 'Ketenagaan Penyuluhan',
            'code' => 'SM.040',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 464,
            'name' => 'Kelembagaan Petani',
            'code' => 'SM.050',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 465,
            'name' => 'Usaha Tani',
            'code' => 'SM.060',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 466,
            'name' => 'Pelatihan Pertanian',
            'code' => 'SM.100',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 467,
            'name' => 'Program dan Kerjasama',
            'code' => 'SM.110',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 468,
            'name' => 'Penyelenggaraan Pelatihan',
            'code' => 'SM.120',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 469,
            'name' => 'Kelembagaan Pelatihan',
            'code' => 'SM.130',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 470,
            'name' => 'Ketenagaan Pelatihan',
            'code' => 'SM.140',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 471,
            'name' => 'Pendidikan, Standarisasi dan Sertifikasi Profesi Pertanian ',
            'code' => 'SM.200',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 472,
            'name' => 'Program Dan Kerjasama',
            'code' => 'SM.210',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 473,
            'name' => 'Penyelenggaraan Pendidikan Pertanian',
            'code' => 'SM.220',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 474,
            'name' => 'Kelembagaan Pendidikan',
            'code' => 'SM.230',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 475,
            'name' => 'Ketenagaan Pendidikan',
            'code' => 'SM.240',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 476,
            'name' => 'Standardisasi Kompetensi',
            'code' => 'SM.250',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 477,
            'name' => 'Sertifikasi Profesi Pertanian',
            'code' => 'SM.260',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 478,
            'name' => 'Kode KU Lama',
            'code' => 'KU',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 479,
            'name' => 'Kode KP Lama',
            'code' => 'KP',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 480,
            'name' => 'Kode RC Lama',
            'code' => 'RC',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => 490,
            'name' => 'Kode TU Lama',
            'code' => 'TU',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        ]);
    }
}
