name: Deploy Production

on:
  push:
    branches:
      - main

concurrency:
  group: production
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy
        run: /opt/deploy/e-arsip.sh